name: Test PSOpenAD
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[github.ref == 'refs/heads/main'] }}

jobs:
  test:
    name: test
    runs-on: ${{ matrix.info.os }}
    strategy:
      fail-fast: false
      matrix:
        info:
        - name: Fedora_37_MIT
          container: fedora:37
          os: ubuntu-latest
          gssapi_provider: mit
        - name: Fedora_37_Heimdal
          container: fedora:37
          os: ubuntu-latest
          gssapi_provider: heimdal

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      shell: bash
      run: >-
        ./tools/run-ci.sh
        '${{ matrix.info.container }}'
        '${{ matrix.info.gssapi_provider }}'
        "${BUILD_CONFIGURATION}"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Results (${{ matrix.info.name }})
        path: ./output/TestResults/Pester.xml

    - name: Upload Coverage Results
      if: always() && !startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Results (${{ matrix.info.name }})
        path: ./output/TestResults/Coverage.xml

    - name: Upload Coverage to codecov
      if: always() && !startsWith(github.ref, 'refs/tags/v')
      uses: codecov/codecov-action@v3
      with:
        files: ./output/TestResults/Coverage.xml
        flags: ${{ matrix.info.name }}

  # Would like to build for testing but it break coverage, need to reinvestigate if this gets fixed.
  # https://github.com/coverlet-coverage/coverlet/issues/1271
  build:
    name: build
    needs:
    - test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Azure OIDC auth
      contents: read  # Repo checkout

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: OIDC Login to Azure
      if: ${{ env.BUILD_CONFIGURATION == 'Release' }}
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build module - Release
      if: ${{ env.BUILD_CONFIGURATION == 'Release' }}
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build
      env:
        AZURE_KEYVAULT_NAME: ${{ secrets.AZURE_KEYVAULT_NAME }}
        AZURE_KEYVAULT_CERT: ${{ secrets.AZURE_KEYVAULT_CERT }}

    - name: Capture PowerShell Module
      uses: actions/upload-artifact@v3
      with:
        name: PSModule
        path: output/*.nupkg
