name: Test PSOpenAD
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

  release:
    types:
    - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[github.ref == 'refs/heads/main' || startsWith(github.event.release.tag_name, 'v')] }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Azure OIDC auth
      contents: read  # Repo checkout

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: OIDC Login to Azure - Release only
      if: startsWith(github.event.release.tag_name, 'v')
      shell: pwsh
      run: |
        $loginParams = @{
            ClientId = '${{ secrets.AZURE_CLIENT_ID }}'
            TenantId = '${{ secrets.AZURE_TENANT_ID }}'
        }
        ./tools/AzLoginOIDC.ps1 @loginParams

    - name: Build module
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build
      env:
        AZURE_TS_NAME: ${{ startsWith(github.event.release.tag_name, 'v') && secrets.AZURE_TS_NAME || '' }}
        AZURE_TS_PROFILE: ${{ startsWith(github.event.release.tag_name, 'v') && secrets.AZURE_TS_PROFILE || '' }}
        AZURE_TS_ENDPOINT: ${{ startsWith(github.event.release.tag_name, 'v') && secrets.AZURE_TS_ENDPOINT || '' }}

    - name: Capture PowerShell Module
      uses: actions/upload-artifact@v7
      with:
        name: PSModule
        path: output/*.nupkg

  test:
    name: test
    needs:
    - build
    runs-on: ${{ matrix.info.os }}
    strategy:
      fail-fast: false
      matrix:
        info:
        - name: Linux_74_MIT
          container: almalinux:10
          os: ubuntu-latest
          gssapi_provider: mit
          psversion: '7.4.0'
        - name: Linux_75_MIT
          container: almalinux:10
          os: ubuntu-latest
          gssapi_provider: mit
          psversion: '7.5.0'
        - name: Linux_76_MIT
          container: almalinux:10
          os: ubuntu-latest
          gssapi_provider: mit
          psversion: '7.6.0'
        - name: Linux_76_Heimdal
          container: almalinux:10
          os: ubuntu-latest
          gssapi_provider: heimdal
          psversion: '7.6.0'

    steps:
    - uses: actions/checkout@v6

    - name: Restore Built PowerShell Module
      uses: actions/download-artifact@v8
      with:
        name: PSModule
        path: output

    - name: Run Tests
      shell: bash
      run: >-
        ./tools/run-ci.sh
        '${{ matrix.info.container }}'
        '${{ matrix.info.gssapi_provider }}'
        "${BUILD_CONFIGURATION}"
        '${{ matrix.info.psversion }}'

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: Unit Test Results (${{ matrix.info.name }})
        path: ./output/TestResults/Pester.xml

    - name: Upload Coverage Results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: Coverage Results (${{ matrix.info.name }})
        path: ./output/TestResults/Coverage.cobertura.xml

    - name: Upload Coverage to codecov
      if: always()
      uses: codecov/codecov-action@v6
      with:
        files: ./output/TestResults/Coverage.cobertura.xml
        flags: ${{ matrix.info.name }}
        token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: publish
    needs:
    - test
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for GitHub release asset task

    steps:
    - name: Restore Built PowerShell Module
      uses: actions/download-artifact@v8
      with:
        name: PSModule
        path: ./

    - name: Upload to release asset
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload \
          "${{ github.event.release.tag_name }}" \
          *.nupkg \
          --repo "${{ github.repository }}"

    - name: Publish to the PowerShell Gallery
      run: >-
        dotnet nuget push *.nupkg
        --api-key "${PSGALLERY_TOKEN}"
        --source "https://www.powershellgallery.com/api/v2/package"
        --no-symbols
      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
